### ISSUE TITLE
Tried to experiment but there are problems with dependencies

### ISSUE THREAD

**Issue by RunninglVlan** [bclozel/spring-reactive-university#4]
I tried adding _spring-boot-starter-web-reactive_'s `<version>0.1.0.M1</version>`, it solved some problems, but I'm missing _WebClient_ and related client lib.

**Comment by melgenek** [comment]
Spring webflux starter is now merged to spring boot repo and renamed.  So now you need "spring-boot-starter-webflux" dependency as well as spring boot 2.0, cause it is not released yet. Visit start.spring.io and generate a project.  
You can check sample grade build file 
https://github.com/melgene/kotlin-spring/blob/master/build.gradle

**Comment by RunninglVlan** [comment]
Thanks, I managed to start the app. Could you check the request #5?
